# Generated by Django 6.0.1 on 2026-03-17 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculoCondenacaoCivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200)),
                ('texto_sentenca', models.TextField()),
                ('parametros_extraidos', models.JSONField(blank=True, default=dict)),
                ('parametros_confirmados', models.JSONField(blank=True, default=dict)),
                ('resultado_calculo', models.JSONField(blank=True, default=dict)),
                ('memoria_calculo', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('extraido', 'Parametros extraidos'), ('calculado', 'Calculado'), ('erro', 'Erro')], default='rascunho', max_length=20)),
                ('provedor_extracao', models.CharField(blank=True, max_length=100)),
                ('modelo_extracao', models.CharField(blank=True, max_length=100)),
                ('observacoes_extracao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calculos_civeis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Calculo de Condenacao Civel',
                'verbose_name_plural': 'Calculos de Condenacao Civel',
                'ordering': ['-atualizado_em'],
            },
        ),
    ]
