# Generated by Django 6.0.1 on 2026-03-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculocondenacaocivel',
            name='arquivo_sentenca_pdf',
            field=models.FileField(blank=True, upload_to='calculadora/sentencas_pdf/%Y/%m/'),
        ),
    ]
