# Generated by Django 6.0.1 on 2026-02-03 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='docgen.setor')),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título da Peça')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição/Instruções')),
                ('arquivo_template', models.FileField(upload_to='templates/')),
                ('configuracao_campos', models.JSONField(default=list, verbose_name='Configuração dos Campos')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='docgen.area', verbose_name='Área')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='docgen.setor', verbose_name='Setor')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoGerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dados_inputados', models.JSONField()),
                ('arquivo_final', models.FileField(blank=True, null=True, upload_to='gerados/')),
                ('data_geracao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='docgen.template')),
            ],
        ),
    ]
