# Generated by Django 6.0.2 on 2026-02-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docgen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
