# Generated by Django 6.0.2 on 2026-02-05 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docgen', '0002_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='docgen.categoria', verbose_name='Tipo de Documento'),
        ),
    ]
