# Generated by Django 6.0.1 on 2026-04-02 12:38

import django.db.models.deletion
import docgen.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docgen', '0004_equipe_pastapersonalizada_templatefavorito'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteImportacaoProcessos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo_planilha', models.FileField(upload_to=docgen.models._upload_lote_processos)),
                ('total_linhas', models.PositiveIntegerField(default=0)),
                ('total_validas', models.PositiveIntegerField(default=0)),
                ('total_invalidas', models.PositiveIntegerField(default=0)),
                ('total_processos_criados', models.PositiveIntegerField(default=0)),
                ('total_processos_atualizados', models.PositiveIntegerField(default=0)),
                ('resultado_importacao', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes_importacao_processos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cnj', models.CharField(max_length=25)),
                ('tribunal_codigo', models.CharField(max_length=4)),
                ('tribunal_nome', models.CharField(max_length=100)),
                ('status_atual', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_FILA', 'Em fila'), ('PROCESSANDO', 'Processando'), ('BAIXADO', 'Baixado'), ('PROCESSO_NAO_ENCONTRADO', 'Processo nao encontrado'), ('PETICAO_NAO_LOCALIZADA', 'Peticao inicial nao localizada'), ('FALHA_TECNICA', 'Falha tecnica')], default='PENDENTE', max_length=40)),
                ('ultima_mensagem', models.TextField(blank=True)),
                ('observacao', models.TextField(blank=True)),
                ('referencia_interna', models.CharField(blank=True, max_length=120)),
                ('ultimo_sucesso_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-atualizado_em'],
            },
        ),
        migrations.CreateModel(
            name='ExecucaoCapturaProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_FILA', 'Em fila'), ('PROCESSANDO', 'Processando'), ('BAIXADO', 'Baixado'), ('PROCESSO_NAO_ENCONTRADO', 'Processo nao encontrado'), ('PETICAO_NAO_LOCALIZADA', 'Peticao inicial nao localizada'), ('FALHA_TECNICA', 'Falha tecnica')], default='PENDENTE', max_length=40)),
                ('worker_id', models.CharField(blank=True, max_length=120)),
                ('tentativa', models.PositiveIntegerField(default=0)),
                ('iniciada_em', models.DateTimeField(blank=True, null=True)),
                ('finalizada_em', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_em', models.DateTimeField(blank=True, null=True)),
                ('mensagem', models.TextField(blank=True)),
                ('tribunal_url', models.URLField(blank=True, max_length=500)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execucoes', to='docgen.loteimportacaoprocessos')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execucoes', to='docgen.processo')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ArquivoProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('peticao_inicial', 'Peticao inicial')], default='peticao_inicial', max_length=40)),
                ('arquivo', models.FileField(upload_to=docgen.models._upload_arquivo_processo)),
                ('atual', models.BooleanField(default=True)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('execucao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='docgen.execucaocapturaprocesso')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='docgen.processo')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='processo',
            index=models.Index(fields=['status_atual', 'tribunal_codigo'], name='docgen_proc_status__e23b69_idx'),
        ),
        migrations.AddConstraint(
            model_name='processo',
            constraint=models.UniqueConstraint(fields=('usuario', 'numero_cnj'), name='uniq_processo_usuario_numero_cnj'),
        ),
        migrations.AddIndex(
            model_name='execucaocapturaprocesso',
            index=models.Index(fields=['status', 'criado_em'], name='docgen_exec_status_30d4cd_idx'),
        ),
        migrations.AddConstraint(
            model_name='arquivoprocesso',
            constraint=models.UniqueConstraint(condition=models.Q(('atual', True)), fields=('processo', 'tipo'), name='uniq_arquivo_processo_atual_por_tipo'),
        ),
    ]
