# Generated by Django 6.0.1 on 2026-07-30 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docgen', '0009_remove_pastapersonalizada_compartilhada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
    ]
