# Generated by Django 6.0.1 on 2026-08-13 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docgen', '0010_template_criado_por'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcessoArquivado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivado_em', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('arquivado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arquivamentos_feitos', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='arquivamento', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acesso arquivado',
                'verbose_name_plural': 'Acessos arquivados',
            },
        ),
    ]
