# Generated by Django 6.0.1 on 2026-08-13 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docgen', '0011_acessoarquivado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VinculoEntraId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_corporativo', models.EmailField(max_length=254)),
                ('vinculado_em', models.DateTimeField(auto_now_add=True)),
                ('conta_absorvida', models.CharField(blank=True, max_length=150)),
                ('itens_migrados', models.PositiveIntegerField(default=0)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vinculo_entra', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vínculo Entra ID',
                'verbose_name_plural': 'Vínculos Entra ID',
            },
        ),
    ]
